// src/components/CustomButton.tsx
import type { JSX, ParentComponent } from "solid-js";
import { splitProps } from "solid-js";
import { twMerge } from "tailwind-merge";

interface Props extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  class?: string;
  type?: "button" | "submit" | "reset";
}
const CustomButton: ParentComponent<Props> = (props) => {
  const [local, others] = splitProps(props, ["class", "type"]);

  return (
    <button
      type={local.type === undefined ? "button" : local.type}
      class={twMerge(
        `m-2 rounded-full p-3 font-semibold text-white transition-all hover:scale-110 active:scale-125 duration-200 ease-in bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 active:bg-blue-600`,
        local.class
      )}
      {...others}
    >
      {props.children}
    </button>
  );
};

export default CustomButton;

// apps/client/src/components/CustomButton.tsx
import { HtmlHTMLAttributes } from "react";
import { twMerge } from "tailwind-merge";

interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string;
  type?: "button" | "submit" | "reset";
  children: React.ReactNode;
}

const CustomButton = ({
  className,
  children,
  type,

  ...rest
}: Props) => {
  const classNameBase = twMerge(
    `rounded-full p-3 m-2 font-semibold text-white
      transition-all active:scale-110 hover:scale-110 bg-blue-500 active:bg-blue-600 hover:bg-blue-600`,
    className
  );
  return (
    <button
      type={type === undefined ? "button" : type}
      {...rest}
      className={classNameBase}
    >
      {children}
    </button>
  );
};

export default CustomButton;
